### ISSUE TITLE
Confusion in data citation examples

### ISSUE THREAD

**Issue by ianschmutte** [AEADataEditor/aea-de-guidance.v1#3]
On the suggested data citations, some readers might not immediately understand two of the examples (pasted below) as describing data citation (they look like working paper citations). Are these supposed to be citations back to the analysis data used in these papers? I guess I was expecting to see citations to primary data sources (e.g. to the NBER extracts of the CPS, or something like that).

    Esther Duflo; Rohini Pande, 2006, ``Dams, Poverty, Public Goods and
    Malaria Incidence in India'', http://hdl.handle.net/1902.1/IOJHHXOOLZ
    UNF:5:obNHHq1gtV400a4T+Xrp9g== Murray Research Archive [Distributor]
    V2 [Version]

Finally, the AEA style guide  suggests

    Leiss, Amelia. 1999. ``Arms Transfers to Developing Countries, 1945--1968.''
    Inter-University Consortium for Political and Social Research, Ann Arbor, MI.
    ICPSR05404-v1. doi:10.3886/ICPSR05404 (accessed February 8, 2011).

**Comment by larsvilhuber** [comment]
Those are, in fact, data citations, and they are literally the examples given on ICPSR page (1) and the AEA page (2).

I don't know how to respond to authors when the actual data archive itself, which is noted as an expert, provides this as the suggested citation....

That being said, context matters as well.



--
Sent from my mobile device


-------- Original message --------

**Comment by larsvilhuber** [comment]
I'll add a data citation for such a data source by a NSO. The Leiss citation actually is different on the AEA pages when compared to the suggested citation. The problem is that Chicago style does not provide an example.

**Comment by larsvilhuber** [comment]
... and to add to confusion, the going interpretation of Chicago style is that you don't add the suffixes "[dataset]" and "[distributor]" or similar...

**Comment by larsvilhuber** [comment]
The page referred to by this issue was migrated to the SocSci guidance. And now solved.
