### ISSUE TITLE
<script> in README.md

### ISSUE THREAD

**Issue by jdingel** [AEADataEditor/aea-de-guidance.v1#6]
There are bits of HTML of the <script> form appearing in README.md that are not rendered by GitHub. The following appears in two places where Twitter is mentioned:

<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by larsvilhuber** [comment]
These do appear in the rendered HTML on https://aeadataeditor.github.io/aea-de-guidance/.
